// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"start/webook/internal/repository"
	"start/webook/internal/repository/cache"
	"start/webook/internal/repository/dao"
	"start/webook/internal/service"
	"start/webook/internal/service/sms/memory"
	"start/webook/internal/web"
	"start/webook/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitGorm()
	userDAO := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDAO)
	userService := service.NewUserServiceImpl(userRepo)
	smsSMS := memory.NewMemory()
	codeService := service.NewCodeService(smsSMS)
	userHandle := web.NewUserHandle(userService, codeService)
	engine := ioc.InitWebServer(userHandle)
	app := &App{
		web: engine,
	}
	return app
}

// wire.go:

var user = wire.NewSet(web.NewUserHandle, service.NewUserServiceImpl, repository.NewUserRepo, dao.NewUserDao)

var code = wire.NewSet(service.NewCodeService, repository.NewCodeRepo, cache.NewCodeCacheRedis)

var sms = wire.NewSet(memory.NewMemory)
