// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	ioc2 "start/webook/bff/ioc"
	"start/webook/bff/web"
	"start/webook/code/_internal/repository"
	"start/webook/code/_internal/repository/cache"
	"start/webook/code/_internal/service"
	"start/webook/sms/_internal/service/sms/memory"
	repository2 "start/webook/user/_internal/repository"
	"start/webook/user/_internal/repository/dao"
	service2 "start/webook/user/_internal/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc2.InitGorm()
	userDAO := dao.NewUserDao(db)
	userRepo := repository2.NewUserRepo(userDAO)
	userService := service2.NewUserServiceImpl(userRepo)
	smsSMS := memory.NewMemory()
	codeService := service.NewCodeService(smsSMS)
	userHandle := web.NewUserHandle(userService, codeService)
	engine := ioc2.InitWebServer(userHandle)
	app := &App{
		web: engine,
	}
	return app
}

// wire.go:

var user = wire.NewSet(web.NewUserHandle, service2.NewUserServiceImpl, repository2.NewUserRepo, dao.NewUserDao)

var code = wire.NewSet(service.NewCodeService, repository.NewCodeRepo, cache.NewCodeCacheRedis)

var sms = wire.NewSet(memory.NewMemory)
