// Code generated by MockGen. DO NOT EDIT.
// Source: interactive.go
//
// Generated by this command:
//
//	mockgen -source=interactive.go -package=svcmocks -destination=mocks/interactive.mock.go InteractiveService
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	domain "start/webook/internal/domain"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockInteractiveService is a mock of InteractiveService interface.
type MockInteractiveService struct {
	ctrl     *gomock.Controller
	recorder *MockInteractiveServiceMockRecorder
	isgomock struct{}
}

// MockInteractiveServiceMockRecorder is the mock recorder for MockInteractiveService.
type MockInteractiveServiceMockRecorder struct {
	mock *MockInteractiveService
}

// NewMockInteractiveService creates a new mock instance.
func NewMockInteractiveService(ctrl *gomock.Controller) *MockInteractiveService {
	mock := &MockInteractiveService{ctrl: ctrl}
	mock.recorder = &MockInteractiveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractiveService) EXPECT() *MockInteractiveServiceMockRecorder {
	return m.recorder
}

// GetIntr mocks base method.
func (m *MockInteractiveService) GetIntr(ctx context.Context, biz string, bizId int64, uid int) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntr", ctx, biz, bizId, uid)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntr indicates an expected call of GetIntr.
func (mr *MockInteractiveServiceMockRecorder) GetIntr(ctx, biz, bizId, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntr", reflect.TypeOf((*MockInteractiveService)(nil).GetIntr), ctx, biz, bizId, uid)
}

// TopN mocks base method.
func (m *MockInteractiveService) TopN(ctx context.Context, now time.Time, batch int) ([]domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopN", ctx, now, batch)
	ret0, _ := ret[0].([]domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopN indicates an expected call of TopN.
func (mr *MockInteractiveServiceMockRecorder) TopN(ctx, now, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopN", reflect.TypeOf((*MockInteractiveService)(nil).TopN), ctx, now, batch)
}
