// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lawOffice/internal/web"
	"lawOffice/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	userHandler := web.NewUserHandler()
	engine := ioc.InitWebServer(userHandler)
	app := &App{
		Server: engine,
	}
	return app
}

// wire.go:

var userServer = wire.NewSet(web.NewUserHandler)
